var found = false;
var amount1 = 45;
var amount2 = 453.54;
var firstName = 'Arun';
var lastName = "Varun";
var anything = 'hi';
console.log("print value of anything variable -" + anything);
anything = 564.6;
console.log("print value of anything variable -" + anything);
anything = true;
console.log("print value of anything variable -" + anything);
console.log("printing other variables value");
console.log(found);
console.log("first amount " + amount1);
console.log("second amount " + amount2);
console.log("whole name - " + firstName + " " + lastName);
console.log("Hi ".concat(firstName, " ").concat(lastName));
